on: 
  workflow_dispatch:
    inputs:
      enviroment:
        description: "chiose enviroment"
        default: "staging"
        required: true
        type: choice
        options:
          - staging
          - production 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Deploye "
        run: echo "Deploye is Enviromner ${{inputs.enviroment}}"
  
          
